image updated

diff --git a/templates/job-create-site.yaml b/templates/job-create-site.yaml
--- a/templates/job-create-site.yaml
+++ b/templates/job-create-site.yaml
@@ -1,97 +1,155 @@
-# Source: erpnext/templates/job-create-site.yaml
+{{- if .Values.jobs.createSite.enabled }}
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: frappe-bench-erpnext-new-site
+  name: {{ template "erpnext.fullname" . }}-new-site-{{ now | date "20060102150405" }}
   labels:
-    helm.sh/chart: erpnext-7.0.15
-    app.kubernetes.io/name: erpnext
-    app.kubernetes.io/instance: frappe-bench
-    app.kubernetes.io/version: "v15.10.0"
-    app.kubernetes.io/managed-by: Helm
+    {{- include "erpnext.labels" . | nindent 4 }}
 spec:
-  backoffLimit: 0
+  backoffLimit: {{ .Values.jobs.createSite.backoffLimit }}
   template:
     spec:
-      serviceAccountName: frappe-bench-erpnext
+    {{- with .Values.imagePullSecrets }}
+      imagePullSecrets:
+        {{- toYaml . | nindent 8 }}
+    {{- end }}
+      serviceAccountName: {{ template "erpnext.serviceAccountName" $ }}
       securityContext:
-        supplementalGroups:
-        - 1000
-        # initContainers:
-        # - name: validate-config
-        #   image: "frappe/erpnext:v15.10.0"
-        #   imagePullPolicy: IfNotPresent
-        # command: ["bash", "-c"]
-        # args:
-        #   - >
-        #     export start=`date +%s`;
-        #     until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
-        #       [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
-        #       [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
-        #     do
-        #       echo "Waiting for sites/common_site_config.json to be created";
-        #       sleep 5;
-        #       if (( `date +%s`-start > 600 )); then
-        #         echo "could not find sites/common_site_config.json with required keys";
-        #         exit 1
-        #       fi
-        #     done;
-        # #     echo "sites/common_site_config.json found";
-        # resources: {}
-        # securityContext:
-        #   capabilities:
-        #     add:
-        #     - CAP_CHOWN
-        # volumeMounts:
-        # - name: sites-dir
-        #   mountPath: /home/frappe/frappe-bench/sites
+        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
+      initContainers:
+        - name: validate-config
+          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
+          imagePullPolicy: {{ .Values.image.pullPolicy }}
+          # command: ["bash", "-c"]
+          # args:
+          #   - >
+          #     export start=`date +%s`;
+          #     until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
+          #       [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
+          #       [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+          #     do
+          #       echo "Waiting for sites/common_site_config.json to be created";
+          #       sleep 5;
+          #       if (( `date +%s`-start > 600 )); then
+          #         echo "could not find sites/common_site_config.json with required keys";
+          #         exit 1
+          #       fi
+          #     done;
+          #     echo "sites/common_site_config.json found";
+          resources:
+            {{- toYaml .Values.jobs.createSite.resources | nindent 12 }}
+          securityContext:
+            {{- toYaml $.Values.securityContext | nindent 12 }}
+          volumeMounts:
+            - name: sites-dir
+              mountPath: /home/frappe/frappe-bench/sites
       containers:
       - name: create-site
-        image: usman89/myrepo:frapee_atd_0.0.3
-        imagePullPolicy: IfNotPresent
+        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
+        imagePullPolicy: {{ .Values.image.pullPolicy }}
         command: ["bash", "-c"]
         args:
-        - >
-          bench new-site $(SITE_NAME)  --db-type=$(DB_TYPE) --db-host=$(DB_HOST) --db-port=$(DB_PORT) --admin-password=$(ADMIN_PASSWORD) --install-app=associated_terminals --db-root-username=$(DB_ROOT_USER) --db-root-password=$(DB_ROOT_PASSWORD)  --force ;rm -f currentsite.txt; bench use erp.info.com; bench --site erp.info.com enable-scheduler;
+          - >
+            bench new-site $(SITE_NAME)  --db-type=$(DB_TYPE) --db-host=$(DB_HOST) --db-port=$(DB_PORT) --admin-password=$(ADMIN_PASSWORD) --install-app=associated_terminals --db-root-username=$(DB_ROOT_USER) --db-root-password=$(DB_ROOT_PASSWORD)  --force ;rm -f currentsite.txt; bench use erp.info.com; bench --site erp.info.com enable-scheduler;
         env:
-        - name: "SITE_NAME"
-          value: "erp.info.com"
-
-        - name: "DB_TYPE"
-          value: postgres
-        - name: "DB_HOST"
-          value: frappe-bench-mariadb
-        - name: "DB_PORT"
-          value: "5432"
-        - name: "DB_ROOT_USER"
-          value: "root"
-        - name: "DB_ROOT_PASSWORD"
-          value: changeit
-          #   secretKeyRef:
-          #     key: db-root-password
-          #     name: frappe-bench
-        - name: "ADMIN_PASSWORD"
-          value: "secret"
-        # - installApps:
-        #   associated_terminals
-        resources: {}
-
+          - name: "SITE_NAME"
+            value: "erp.info.com"
+          - name: "DB_TYPE"
+            value: {{ .Values.jobs.createSite.dbType }}
+          - name: "DB_HOST"
+            {{- if .Values.postgresql.host }}
+            value: {{ .Values.postgresql.host }}
+            {{- else if .Values.postgresql.enabled }}
+            value: {{ .Release.Name }}-postgresql
+            {{- else if .Values.mariadb.enabled }}
+            {{- if eq .Values.mariadb.architecture "replication" }}
+            value: {{ .Release.Name }}-mariadb-primary
+            {{- else }}
+            value: {{ .Release.Name }}-mariadb
+            {{- end }}
+            {{- else }}
+            value: "{{ .Values.dbHost }}"
+            {{- end }}
+          - name: "DB_PORT"
+            {{- if .Values.dbPort }}
+            value: {{ .Values.dbPort | quote }}
+            {{- else if .Values.postgresql.enabled }}
+            value: {{ .Values.postgresql.primary.service.ports.postgresql | quote }}
+            {{- else }}
+            value: {{ .Values.mariadb.primary.service.ports.mysql | quote }}
+            {{- end }}
+          - name: "DB_ROOT_USER"
+            {{- if .Values.dbRootUser }}
+            value: "{{ .Values.dbRootUser }}"
+            {{- else if .Values.postgresql.enabled }}
+            value: "postgres"
+            {{- else if .Values.mariadb.enabled }}
+            value: "root"
+            {{- end }}
+          - name: "DB_ROOT_PASSWORD"
+            {{- if .Values.dbRootPassword }}
+            valueFrom:
+              secretKeyRef:
+                key:  db-root-password
+                name: {{ .Release.Name }}
+            {{- else if .Values.postgresql.enabled }}
+            valueFrom:
+              secretKeyRef:
+                key: postgres-password
+                name: {{ .Release.Name }}-postgresql
+            {{- else if .Values.mariadb.enabled }}
+            valueFrom:
+              secretKeyRef:
+                key: mariadb-root-password
+                name: {{ .Release.Name }}-mariadb
+            {{- end }}
+          - name: "ADMIN_PASSWORD"
+            value: "{{ .Values.jobs.createSite.adminPassword }}"
+        resources:
+          {{- toYaml .Values.jobs.createSite.resources | nindent 10 }}
         securityContext:
-          capabilities:
-            add:
-            - CAP_CHOWN
+          {{- toYaml $.Values.securityContext | nindent 10 }}
         volumeMounts:
-        - name: sites-dir
-          mountPath: /home/frappe/frappe-bench/sites
-          # - name: logs
-          #   mountPath: /home/frappe/frappe-bench/logs
+          - name: sites-dir
+            mountPath: /home/frappe/frappe-bench/sites
+          - name: logs
+            mountPath: /home/frappe/frappe-bench/logs
       restartPolicy: Never
       volumes:
-      - name: sites-dir
-        persistentVolumeClaim:
-          claimName: frappe-bench-erpnext
-          readOnly: false
-      # - name: logs
-      #   persistentVolumeClaim:
-      #     claimName: frappe-bench-erpnext-logs
-      #     readOnly: false
+        - name: sites-dir
+          {{- if .Values.persistence.worker.enabled }}
+          persistentVolumeClaim:
+            {{- if .Values.persistence.worker.existingClaim }}
+            claimName: {{ .Values.persistence.worker.existingClaim }}
+            {{- else }}
+            claimName: {{ template "erpnext.fullname" . }}
+            {{- end }}
+            readOnly: false
+          {{- else }}
+          emptyDir: {}
+          {{- end }}
+        - name: logs
+          {{- if .Values.persistence.logs.enabled }}
+          persistentVolumeClaim:
+            {{- if .Values.persistence.logs.existingClaim }}
+            claimName: {{ .Values.persistence.logs.existingClaim }}
+            {{- else }}
+            claimName: {{ template "erpnext.fullname" . }}-logs
+            {{- end }}
+            readOnly: false
+          {{- else }}
+          emptyDir: {}
+          {{- end }}
+      {{- with .Values.jobs.createSite.nodeSelector }}
+      nodeSelector:
+        {{- toYaml . | nindent 8 }}
+      {{- end }}
+      {{- with .Values.jobs.createSite.affinity }}
+      affinity:
+        {{- toYaml . | nindent 8 }}
+      {{- end }}
+      {{- with .Values.jobs.createSite.tolerations }}
+      tolerations:
+        {{- toYaml . | nindent 8 }}
+      {{- end }}
+{{- end }}
