image updated

diff --git a/templates/job-create-site.yaml b/templates/job-create-site.yaml
--- a/templates/job-create-site.yaml
+++ b/templates/job-create-site.yaml
@@ -20,22 +20,45 @@ spec:
         - name: validate-config
           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
           imagePullPolicy: {{ .Values.image.pullPolicy }}
-          # command: ["bash", "-c"]
-          # args:
-          #   - >
-          #     export start=`date +%s`;
-          #     until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
-          #       [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
-          #       [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
-          #     do
-          #       echo "Waiting for sites/common_site_config.json to be created";
-          #       sleep 5;
-          #       if (( `date +%s`-start > 600 )); then
-          #         echo "could not find sites/common_site_config.json with required keys";
-          #         exit 1
-          #       fi
-          #     done;
-          #     echo "sites/common_site_config.json found";
+          command: ["bash", "-c"]
+          args:
+            - >
+              wait-for-it -t 120 db:3306;
+              wait-for-it -t 120 redis-cache:6379;
+              wait-for-it -t 120 redis-queue:6379;
+              export start=`date +%s`;
+              until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
+                [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
+                [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+              do
+                echo "Waiting for sites/common_site_config.json to be created";
+                sleep 5
+                if (( `date +%s`-start > 120 )); then
+                  echo "could not find sites/common_site_config.json with required keys";
+                  exit 1
+                fi
+              done;
+              echo "sites/common_site_config.json found";
+              bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=admin --set-default atd.mmis.space;
+              pwd;
+              bash -c '
+                cd apps
+                cd associated_terminals
+                pwd
+                if [ "git rev-parse HEAD" == "git ls-remote upstream HEAD" ]; then
+                  echo "Local and remote Git repositories are in sync."
+                else
+                  echo "Local and remote Git repositories are not in sync."
+                  git stash
+                  git pull
+                  yarn build
+                fi
+                bench --site atd.mmis.space install-app associated_terminals;
+                bench --site atd.mmis.space migrate;
+                bench config set-common-config -c enable_frappe_logger true;
+                bench set-config cors_allow_origin "*";
+                bench set-config ignore_csrf 1;
+                ';
           resources:
             {{- toYaml .Values.jobs.createSite.resources | nindent 12 }}
           securityContext:
